// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl136dQfOfsBLvG1d9Carvwh0W16H6fac',
    appId: '1:784742646626:web:51d63237c4c6b46cd8223b',
    messagingSenderId: '784742646626',
    projectId: 'chatapp-43acc',
    authDomain: 'chatapp-43acc.firebaseapp.com',
    storageBucket: 'chatapp-43acc.firebasestorage.app',
    measurementId: 'G-M6W9B57LFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwoDc66Gy7fHzV_zXdptwMZTiADM4DL0I',
    appId: '1:784742646626:android:f49decca290ad6a8d8223b',
    messagingSenderId: '784742646626',
    projectId: 'chatapp-43acc',
    storageBucket: 'chatapp-43acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjPOftzIxR8P3nv0ONu6pcJkfGMx9OFA',
    appId: '1:784742646626:ios:4d427de3ac0023d7d8223b',
    messagingSenderId: '784742646626',
    projectId: 'chatapp-43acc',
    storageBucket: 'chatapp-43acc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjPOftzIxR8P3nv0ONu6pcJkfGMx9OFA',
    appId: '1:784742646626:ios:4d427de3ac0023d7d8223b',
    messagingSenderId: '784742646626',
    projectId: 'chatapp-43acc',
    storageBucket: 'chatapp-43acc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl136dQfOfsBLvG1d9Carvwh0W16H6fac',
    appId: '1:784742646626:web:955f451c2840a2c5d8223b',
    messagingSenderId: '784742646626',
    projectId: 'chatapp-43acc',
    authDomain: 'chatapp-43acc.firebaseapp.com',
    storageBucket: 'chatapp-43acc.firebasestorage.app',
    measurementId: 'G-F8H10DTGRF',
  );
}
